# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a83b5a1ad23e0dac196e10317f2c89cb45ec438897b14cece4a1e876d784d171733ca07d84fb395fedd1682723f17025389c36f25fed2e0553085b676df21656

test:
  secret_key_base: 902e11cf597cb5ebf5378e302a4610cda0e32458354767bf412081a3d925232bdc1d334cc52541de6b936816965fc36c609b2fcd2894fbd8c4943f7915929992

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
